# Generated by Django 5.1.3 on 2024-11-21 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_postcomment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComment',
            new_name='Comment',
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name_plural': 'comments'},
        ),
    ]
